<#
.SYNOPSIS
  Send sample security audit events to the SecurityAudit_CL custom table via
  the Logs Ingestion API.

.DESCRIPTION
  Demonstrates custom log ingestion into Log Analytics via DCE + DCR.
  Uses the currently logged-in Azure CLI identity to authenticate.

  PREREQUISITE: The calling identity needs the "Monitoring Metrics Publisher"
  role on the DCR (dcr-amlab-customlogs). This is assigned automatically by
  scripts/post-deploy.ps1, but RBAC propagation on the Monitor data plane
  can take up to 30 minutes after initial assignment.

.PARAMETER ResourceGroup
  Resource group containing the demo lab.

.PARAMETER Count
  Number of sample events to send (default: 10).
#>
param(
  [string]$ResourceGroup = 'rg-azure-monitor-lab',
  [int]$Count = 10
)

$ErrorActionPreference = 'Stop'

Write-Host "`n=== Custom Logs Ingestion Demo ===" -ForegroundColor Cyan

# --- Discover DCE endpoint and DCR immutable ID ---
Write-Host "Looking up Data Collection Endpoint and Rule..." -ForegroundColor Yellow

# List DCEs and filter in PowerShell (avoids JMESPath bracket issues on Windows)
$allDce = az resource list -g $ResourceGroup --resource-type "Microsoft.Insights/dataCollectionEndpoints" -o json | ConvertFrom-Json
$dce = ($allDce | Where-Object { $_.name -like '*customlogs*' }).name
if (-not $dce) { throw "DCE for custom logs not found in $ResourceGroup" }

$dceProps = az resource show -g $ResourceGroup -n $dce --resource-type Microsoft.Insights/dataCollectionEndpoints --api-version 2023-03-11 --query properties -o json | ConvertFrom-Json
$dceEndpoint = $dceProps.logsIngestion.endpoint

# List DCRs and filter in PowerShell
$allDcr = az resource list -g $ResourceGroup --resource-type "Microsoft.Insights/dataCollectionRules" -o json | ConvertFrom-Json
$dcr = ($allDcr | Where-Object { $_.name -like '*customlogs*' }).name
if (-not $dcr) { throw "DCR for custom logs not found in $ResourceGroup" }

$dcrProps = az resource show -g $ResourceGroup -n $dcr --resource-type Microsoft.Insights/dataCollectionRules --api-version 2023-03-11 --query properties -o json | ConvertFrom-Json
$dcrImmutableId = $dcrProps.immutableId

Write-Host "  DCE endpoint:    $dceEndpoint" -ForegroundColor Gray
Write-Host "  DCR immutable ID: $dcrImmutableId" -ForegroundColor Gray

# --- Get auth token ---
Write-Host "Acquiring auth token..." -ForegroundColor Yellow
$tokenJson = az account get-access-token --resource "https://monitor.azure.com/" -o json | ConvertFrom-Json
$token = $tokenJson.accessToken

# --- Generate sample events ---
Write-Host "Generating $Count sample security audit events..." -ForegroundColor Yellow

$eventTypes  = @('Login', 'AccessDenied', 'PrivilegeEscalation', 'ConfigChange', 'DataExport', 'MFAChallenge')
$severities  = @('Info', 'Warning', 'Critical')
$users       = @('alice@contoso.com', 'bob@contoso.com', 'svc-backup@contoso.com', 'admin@contoso.com')
$ips         = @('10.0.1.42', '10.0.2.17', '192.168.1.100', '203.0.113.55', '198.51.100.22')
$resources   = @('/subscriptions/xxx/resourceGroups/prod/providers/Microsoft.Sql/servers/sqlprod',
                  '/subscriptions/xxx/resourceGroups/prod/providers/Microsoft.KeyVault/vaults/kv-prod',
                  '/subscriptions/xxx/resourceGroups/prod/providers/Microsoft.Storage/storageAccounts/stprod',
                  '/subscriptions/xxx/resourceGroups/prod/providers/Microsoft.Compute/virtualMachines/vm-web01')
$actions     = @('Read', 'Write', 'Delete', 'Execute', 'Elevate')
$results     = @('Success', 'Denied', 'Error')

$events = @()
for ($i = 0; $i -lt $Count; $i++) {
  $events += @{
    TimeGenerated  = (Get-Date).AddMinutes(-$i).ToUniversalTime().ToString('o')
    EventType      = $eventTypes | Get-Random
    Severity       = $severities | Get-Random
    UserPrincipal  = $users | Get-Random
    SourceIP       = $ips | Get-Random
    Resource       = $resources | Get-Random
    Action         = $actions | Get-Random
    Result         = $results | Get-Random
    Details        = "Sample event $($i+1) generated by send-custom-logs.ps1"
  }
}

$body = $events | ConvertTo-Json -AsArray -Depth 3

# --- Send to Logs Ingestion API ---
$uri = "$dceEndpoint/dataCollectionRules/$dcrImmutableId/streams/Custom-SecurityAudit_CL?api-version=2023-01-01"

Write-Host "Sending $Count events to Logs Ingestion API..." -ForegroundColor Yellow
Write-Host "  URI: $uri" -ForegroundColor Gray

$response = Invoke-WebRequest -Method POST -Uri $uri `
  -Headers @{ Authorization = "Bearer $token"; 'Content-Type' = 'application/json' } `
  -Body $body

if ($response.StatusCode -eq 204) {
  Write-Host "`nSent $Count events to SecurityAudit_CL. They will appear in ~2-5 min." -ForegroundColor Green
  Write-Host "  Query:  SecurityAudit_CL | where TimeGenerated > ago(15m) | order by TimeGenerated desc" -ForegroundColor Gray
} else {
  Write-Host "Unexpected status: $($response.StatusCode)" -ForegroundColor Red
  Write-Host $response.Content
}
