<#
.SYNOPSIS
  Creates 3 service principals with different Granular RBAC levels for the demo.

.DESCRIPTION
  SP1 (workspace-level): Log Analytics Reader — sees all tables, all rows.
  SP2 (table-level):     AMLAB - Granular Log Reader + ABAC — sees SecurityAudit_CL only.
  SP3 (row-level):       AMLAB - Granular Log Reader + ABAC — sees SecurityAudit_CL, Severity==Critical only.

  Credentials are saved to scripts/.rbac-demo-config.json (git-ignored).
  Run demo-granular-rbac.ps1 afterwards to demonstrate the different access levels.

  IMPORTANT: ABAC conditions take up to 15 minutes to propagate after assignment.

.PARAMETER ResourceGroup
  Resource group name. Default: rg-azure-monitor-lab.

.PARAMETER WorkspaceName
    Log Analytics workspace name. When omitted, discovers the central workspace in the resource group.

.EXAMPLE
  ./scripts/setup-rbac-demo.ps1
#>
param(
    [string]$ResourceGroup  = 'rg-azure-monitor-lab',
    [string]$WorkspaceName  = ''
)

$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Pre-flight: verify subscription (reads expected sub from .azure-target.json,
# which is generated by scripts/sync-config.ps1 from lab.config.json).
# ---------------------------------------------------------------------------
$targetFile = Join-Path $PSScriptRoot '..' '.azure-target.json'
if (-not (Test-Path $targetFile)) {
    Write-Error ".azure-target.json not found. Bootstrap with: Copy-Item lab.config.json.example lab.config.json; edit it; then run scripts/sync-config.ps1."
    return
}
$expectedSub = (Get-Content -Raw $targetFile | ConvertFrom-Json).expectedSubscriptionId
$currentSub  = az account show --query id -o tsv
if ($currentSub -ne $expectedSub) {
    Write-Error "Wrong subscription ($currentSub). Expected $expectedSub. Run: az account set --subscription $expectedSub"
    return
}

# ---------------------------------------------------------------------------
# Gather workspace info
# ---------------------------------------------------------------------------
Write-Host "`n=== Gathering workspace info ===" -ForegroundColor Cyan
if ([string]::IsNullOrWhiteSpace($WorkspaceName)) {
    $workspaces = az monitor log-analytics workspace list -g $ResourceGroup -o json | ConvertFrom-Json
    $centralWorkspace = @($workspaces | Where-Object { $_.name -match '^law-.+-central(?:-|$)' }) | Select-Object -First 1
    if (-not $centralWorkspace) {
        throw "Could not discover the central Log Analytics workspace in resource group '$ResourceGroup'. Pass -WorkspaceName explicitly."
    }
    $WorkspaceName = $centralWorkspace.name
}
$ws = az monitor log-analytics workspace show -g $ResourceGroup -n $WorkspaceName -o json | ConvertFrom-Json
$workspaceId         = $ws.customerId   # GUID — used for API queries
$workspaceResourceId = $ws.id           # ARM resource ID — used for role assignments
$tenantId            = az account show --query tenantId -o tsv
$resourceGroupId      = az group show -n $ResourceGroup --query id -o tsv

$customRoles = az role definition list --custom-role-only true -o json | ConvertFrom-Json
$granularRole = @($customRoles | Where-Object {
    $_.roleName -like 'AMLAB - Granular Log Reader*' -and
    @($_.assignableScopes) -contains $resourceGroupId
}) | Select-Object -First 1
if (-not $granularRole) {
    throw "Could not find the AMLAB Granular Log Reader role assigned to resource group '$ResourceGroup'. Confirm the security posture stage was deployed."
}

Write-Host "  Workspace ID : $workspaceId"
Write-Host "  Resource ID  : $workspaceResourceId"
Write-Host "  Tenant ID    : $tenantId"
Write-Host "  Custom role  : $($granularRole.roleName)"

# ---------------------------------------------------------------------------
# Define the 3 service principals
# ---------------------------------------------------------------------------
$spDefs = @(
    @{ key = 'workspace'; displayName = 'amlab-rbac-sp-workspace'; tier = 'Workspace-level' }
    @{ key = 'table';     displayName = 'amlab-rbac-sp-table';     tier = 'Table-level'     }
    @{ key = 'row';       displayName = 'amlab-rbac-sp-row';       tier = 'Row-level'       }
)

$credentials = @{}

foreach ($def in $spDefs) {
    Write-Host "`n=== [$($def.tier)] Creating SP: $($def.displayName) ===" -ForegroundColor Cyan

    # Check if app registration already exists
    $existing = az ad app list --display-name $def.displayName --query "[0].appId" -o tsv 2>$null
    if ($existing) {
        Write-Host "  App already exists (appId: $existing) — resetting credentials" -ForegroundColor Yellow
        $appId    = $existing
        $spObject = az ad sp list --filter "appId eq '$appId'" --query "[0].id" -o tsv
    } else {
        # Create app registration
        $appJson = az ad app create --display-name $def.displayName -o json | ConvertFrom-Json
        $appId   = $appJson.appId
        Write-Host "  Created app: $appId"

        # Create service principal
        $spJson   = az ad sp create --id $appId -o json | ConvertFrom-Json
        $spObject = $spJson.id
        Write-Host "  Created SP:  $spObject"
    }

    # Create/reset client secret (1 year validity)
    $secretJson = az ad app credential reset --id $appId --display-name 'demo-secret' --years 1 -o json | ConvertFrom-Json

    $credentials[$def.key] = @{
        displayName = $def.displayName
        appId       = $appId
        secret      = $secretJson.password
        spObjectId  = $spObject
    }

    Write-Host "  App ID      : $appId"
    Write-Host "  SP Object ID: $spObject"
    Write-Host "  Secret      : ********" -ForegroundColor DarkGray
}

# ---------------------------------------------------------------------------
# Assign roles
# ---------------------------------------------------------------------------
Write-Host "`n=== Assigning roles ===" -ForegroundColor Cyan

# SP1: Log Analytics Reader (built-in, no conditions)
Write-Host "  [Workspace] Log Analytics Reader → $($credentials['workspace'].displayName)"
az role assignment create `
    --assignee-object-id $credentials['workspace'].spObjectId `
    --assignee-principal-type ServicePrincipal `
    --role 'Log Analytics Reader' `
    --scope $workspaceResourceId `
    -o none 2>$null

# SP2: Granular Reader + ABAC table condition (SecurityAudit_CL only)
Write-Host "  [Table]     Granular Reader + ABAC (SecurityAudit_CL) → $($credentials['table'].displayName)"
$tableCondition = "((!(ActionMatches{'Microsoft.OperationalInsights/workspaces/tables/data/read'})) OR (@Resource[Microsoft.OperationalInsights/workspaces/tables:name] StringEquals 'SecurityAudit_CL'))"

az role assignment create `
    --assignee-object-id $credentials['table'].spObjectId `
    --assignee-principal-type ServicePrincipal `
    --role $granularRole.id `
    --scope $workspaceResourceId `
    --condition $tableCondition `
    --condition-version '2.0' `
    -o none 2>$null

# SP3: Granular Reader + ABAC row condition (SecurityAudit_CL + Severity==Critical)
Write-Host "  [Row]       Granular Reader + ABAC (Severity==Critical) → $($credentials['row'].displayName)"
$rowCondition = '((!(ActionMatches{''Microsoft.OperationalInsights/workspaces/tables/data/read''})) OR ((@Resource[Microsoft.OperationalInsights/workspaces/tables:name] StringEquals ''SecurityAudit_CL'') AND (@Resource[Microsoft.OperationalInsights/workspaces/tables/record:Severity<$key_case_sensitive$>] StringEquals ''Critical'')))'

az role assignment create `
    --assignee-object-id $credentials['row'].spObjectId `
    --assignee-principal-type ServicePrincipal `
    --role $granularRole.id `
    --scope $workspaceResourceId `
    --condition $rowCondition `
    --condition-version '2.0' `
    -o none 2>$null

# ---------------------------------------------------------------------------
# Save config
# ---------------------------------------------------------------------------
$configPath = Join-Path $PSScriptRoot '.rbac-demo-config.json'
$config = @{
    tenantId            = $tenantId
    workspaceId         = $workspaceId
    workspaceResourceId = $workspaceResourceId
    servicePrincipals   = $credentials
}
$config | ConvertTo-Json -Depth 4 | Set-Content $configPath

Write-Host "`n✅ Setup complete!" -ForegroundColor Green
Write-Host "   Config saved to: $configPath" -ForegroundColor Green
Write-Host "   ⚠️  ABAC conditions need up to 15 minutes to propagate." -ForegroundColor Yellow
Write-Host "   ⚠️  This file contains secrets — it is git-ignored." -ForegroundColor Yellow
Write-Host "`n   Next: ./scripts/demo-granular-rbac.ps1" -ForegroundColor Cyan
